#!/bin/bash
curl -s https://duckduckgo.com/html/?q=$(echo "$@" | sed s/\ /+/g) \
    | grep -A 4 results_links_deep \
    | grep -o "href=\".*\"" \
    | sed s/href=// \
    | sed s/\"//g \
    | sed 1q
