#!/usr/bin/env node
(function (sys, exec, _) {
    var git_status = exec('git status', function (error, stdout, stderr) {
        sys.print('stdout: ' + stdout);
        sys.print('stderr: ' + stderr);
        if (error !== null && error !== undefined) {
            console.log('exec error: ' + error);
        }
    });
}(require('sys'), require('child_process').exec, require('lodash')));
